CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE_ROLE_CENTRAL=y
CONFIG_I2C=y
CONFIG_GPIO=y
CONFIG_GPIO_MCP230XX=y
CONFIG_ZMK_POINTING=y
CONFIG_INPUT=y

# Turn on the external Azoteq trackpad driver
CONFIG_INPUT_AZOTEQ_IQS5XX=y
