on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        uses: zmkfirmware/zmk-build-action@main
        with:
          board: xiao_ble
          shield: ergo_right
